/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/tryfrege/EditorFragment.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.tryfrege;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Concurrent;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import froid.Types;
import froid.app.Activity;
import froid.content.Context;
import froid.content.Intent;
import froid.content.res.AssetManager;
import froid.content.res.Configuration;
import froid.graphics.Typeface;
import froid.os.Bundle;
import froid.support.v4.app.Fragment;
import froid.support.v4.app.FragmentManager;
import froid.support.v4.app.FragmentTransaction;
import froid.support.v4.view.PagerAdapter;
import froid.support.v4.view.ViewPager;
import froid.support.v7.app.ActionBar;
import froid.support.v7.app.AppCompatActivity;
import froid.support.v7.widget.Toolbar;
import froid.text.Editable;
import froid.text.TextWatcher;
import froid.util.Log;
import froid.view.ContextMenu;
import froid.view.LayoutInflater;
import froid.view.Menu;
import froid.view.MenuInflater;
import froid.view.MenuItem;
import froid.view.View;
import froid.view.ViewGroup;
import froid.view.animation.Animation;
import froid.widget.LineNumberEditText;
import froid.widget.TextView;
import io.github.mchav.tryfrege.Net;
import io.github.mchav.tryfrege.Utilities;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\tryfrege\\EditorFragment.fr", time=1539569107516L, jmajor=1,
  jminor=7,
  imps={
    "froid.support.v7.app.AppCompatActivity", "froid.os.Bundle", "frege.control.Concurrent", "froid.content.Context",
    "froid.text.Editable", "froid.support.v4.app.Fragment", "froid.view.LayoutInflater",
    "froid.widget.LineNumberEditText", "froid.util.Log", "io.github.mchav.tryfrege.Net", "frege.Prelude",
    "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeIO", "frege.prelude.PreludeList",
    "frege.prelude.PreludeMonad", "frege.prelude.PreludeText", "frege.java.util.Regex", "froid.widget.TextView",
    "froid.text.TextWatcher", "io.github.mchav.tryfrege.Utilities", "froid.view.View", "froid.view.ViewGroup",
    "froid.support.v4.view.ViewPager"
  },
  nmss={
    "AppCompatActivity", "Bundle", "Concurrent", "Context", "Editable", "Fragment", "LayoutInflater",
    "LineNumberEditText", "Log", "Net", "Prelude", "PreludeArrays", "PreludeBase", "PreludeIO",
    "PreludeList", "PreludeMonad", "PreludeText", "Regexp", "TextView", "TextWatcher", "Utilities",
    "View", "ViewGroup", "ViewPager"
  },
  symas={}, symcs={}, symis={}, symts={},
  symvs={
    @Meta.SymV(
      offset=902, name=@Meta.QName(pack="io.github.mchav.tryfrege.EditorFragment", base="onCreateView"),
      stri="s(uuuussu)", sig=7, depth=7, rkind=49
    ),
    @Meta.SymV(
      offset=587, name=@Meta.QName(pack="io.github.mchav.tryfrege.EditorFragment", base="newEditorFragment"),
      stri="s(uuu)", sig=8, depth=3, rkind=49
    ),
    @Meta.SymV(
      offset=1488, name=@Meta.QName(pack="io.github.mchav.tryfrege.EditorFragment", base="evaluateInput"),
      stri="s(suuu)", sig=10, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=2216, name=@Meta.QName(pack="io.github.mchav.tryfrege.EditorFragment", base="alertError"), stri="s(su)",
      sig=12, depth=2, rkind=49
    )
  },
  symls={},
  taus={
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.control.Concurrent", base="MVar")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=1, subb=2), @Meta.Tau(kind=0, suba=0, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=5, subb=6),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.support.v4.view.ViewPager", base="ViewPager")}),
    @Meta.Tau(kind=0, suba=7, subb=8),
    @Meta.Tau(
      kind=2, suba=0,
      tcon={@Meta.QName(kind=0, pack="froid.support.v7.app.AppCompatActivity", base="AppCompatActivity")}
    ),
    @Meta.Tau(kind=0, suba=7, subb=10),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.support.v4.app.Fragment", base="Fragment")}),
    @Meta.Tau(kind=0, suba=7, subb=12),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.view.LayoutInflater", base="LayoutInflater")}),
    @Meta.Tau(kind=0, suba=7, subb=14),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.view.ViewGroup", base="ViewGroup")}),
    @Meta.Tau(kind=0, suba=7, subb=16),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Maybe")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.os.Bundle", base="Bundle")}),
    @Meta.Tau(kind=0, suba=7, subb=19), @Meta.Tau(kind=0, suba=18, subb=20),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=22, subb=6),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.view.View", base="View")}),
    @Meta.Tau(kind=0, suba=7, subb=24), @Meta.Tau(kind=0, suba=23, subb=25), @Meta.Tau(kind=0, suba=23, subb=13),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.widget.LineNumberEditText", base="LineNumberEditText")}
    ),
    @Meta.Tau(kind=0, suba=7, subb=28),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=23, subb=30)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=4), @Meta.Rho(rhofun=false, rhotau=9), @Meta.Rho(rhofun=false, rhotau=11),
    @Meta.Rho(rhofun=false, rhotau=13), @Meta.Rho(rhofun=false, rhotau=15), @Meta.Rho(rhofun=false, rhotau=17),
    @Meta.Rho(rhofun=false, rhotau=21), @Meta.Rho(rhofun=false, rhotau=26), @Meta.Rho(sigma=6, rhotau=7),
    @Meta.Rho(sigma=5, rhotau=8), @Meta.Rho(sigma=4, rhotau=9), @Meta.Rho(sigma=3, rhotau=10),
    @Meta.Rho(sigma=2, rhotau=11), @Meta.Rho(sigma=1, rhotau=12), @Meta.Rho(sigma=0, rhotau=13),
    @Meta.Rho(rhofun=false, rhotau=27), @Meta.Rho(sigma=2, rhotau=15), @Meta.Rho(sigma=1, rhotau=16),
    @Meta.Rho(sigma=0, rhotau=17), @Meta.Rho(rhofun=false, rhotau=29), @Meta.Rho(rhofun=false, rhotau=31),
    @Meta.Rho(sigma=9, rhotau=20), @Meta.Rho(sigma=2, rhotau=21), @Meta.Rho(sigma=1, rhotau=22),
    @Meta.Rho(sigma=0, rhotau=23), @Meta.Rho(rhofun=false, rhotau=3), @Meta.Rho(sigma=11, rhotau=20),
    @Meta.Rho(sigma=2, rhotau=26)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=1), @Meta.Sigma(rho=2), @Meta.Sigma(rho=3), @Meta.Sigma(rho=4),
    @Meta.Sigma(rho=5), @Meta.Sigma(rho=6), @Meta.Sigma(rho=14), @Meta.Sigma(rho=18), @Meta.Sigma(rho=19),
    @Meta.Sigma(rho=24), @Meta.Sigma(rho=25), @Meta.Sigma(rho=27)
  },
  exprs={@Meta.Expr()}
)
final public class EditorFragment  {
  




final public static Func.U<RealWorld, Short> alertError(
  final froid.support.v7.app.FregeAppCompatActivity arg$1, final Lazy<String/*<Character>*/> arg$2
) {
  final Func.U<RealWorld, android.app.AlertDialog.Builder> v2038$8545 = Utilities.TAlertDialogBuilder.$new(
        (android.content.Context)arg$1
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8633) {
          final android.app.AlertDialog.Builder v2041$8548 = v2038$8545.apply(arg$8633)
          .call();
          final Func.U<RealWorld, android.app.AlertDialog> v2038$8567 = Utilities.TAlertDialogBuilder.create(
                v2041$8548
              );
          final android.app.AlertDialog v2041$8570 = v2038$8567.apply(arg$8633).call();
          final Func.U<RealWorld, Short> v4801$8616 = Utilities.TAlertDialog.setMessage(
                v2041$8570, arg$2.call()
              );
          final Func.U<RealWorld, Short> v4801$8592 = Utilities.TAlertDialog.setTitle(
                v2041$8570, "Error"
              );
          final short v4804$8594 = (short)v4801$8592.apply(arg$8633).call();
          final Func.U<RealWorld, Short> v4805$8595 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8638) {
              final short v4804$8618 = (short)v4801$8616.apply(arg$8638).call();
              final Func.U<RealWorld, Short> v4805$8619 = Thunk.<Func.U<RealWorld, Short>>shared(
                    new Lazy.D<Func.U<RealWorld, Short>>() {
                      public Func.U<RealWorld, Short> call() {
                        return Utilities.TAlertDialog.show(v2041$8570);
                      }
                    }
                  ).call();
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v4805$8619.apply(arg$8638);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8595.apply(arg$8633);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, Short> evaluateInput(
  final java.util.concurrent.BlockingQueue<String/*<Character>*/> arg$1, final Lazy<android.support.v4.view.ViewPager> arg$2,
  final Lazy<froid.support.v7.app.FregeAppCompatActivity> arg$3, final Lazy<me.mgottein.LineNumberEditText> arg$4
) {
  final Func.U<RealWorld, String/*<Character>*/> v2038$8342 = Concurrent.TMVar.<String/*<Character>*/>take(
        arg$1
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8645) {
          final String/*<Character>*/ v2041$8345 = v2038$8342.apply(arg$8645).call();
          final Func.U<RealWorld, String/*<Character>*/> v2038$8410 = Utilities.<String/*<Character>*/>readMVar(
                arg$1
              );
          final Func.U<RealWorld, String/*<Character>*/> v2038$8388 = Net.getSessionID
          .call();
          final Func.U<RealWorld, Short> v4801$8367 = Concurrent.forkIO(
                new Func.U.D<RealWorld, Short>() {
                  public Lazy<Short> apply(final Lazy<RealWorld> arg$8669) {
                    final String/*<Character>*/ v2041$8391 = v2038$8388.apply(arg$8669)
                    .call();
                    final Func.U<RealWorld, Short> v2042$8392 = Concurrent.TMVar.<String/*<Character>*/>put(
                          arg$1, v2041$8391
                        );
                    return Thunk.<Short>nested(
                              new Lazy.D<Lazy<Short>>() {
                                public Lazy<Short> call() {
                                  return v2042$8392.apply(arg$8669);
                                }
                              }
                            );
                  }
                }
              );
          final short v4804$8369 = (short)v4801$8367.apply(arg$8645).call();
          final Func.U<RealWorld, Short> v4805$8370 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8649) {
              final String/*<Character>*/ v2041$8413 = v2038$8410.apply(arg$8649).call();
              final Func.U<RealWorld, String/*<Character>*/> v2038$8432 = Func.<RealWorld, String/*<Character>*/>coerceU(
                    PreludeMonad.<Func.U<RealWorld, ?>, CharSequence, String/*<Character>*/>liftM(
                          PreludeMonad.IMonad_ST.<RealWorld>mk(),
                          new Func.U.D<CharSequence, String/*<Character>*/>() {
                            public Lazy<String/*<Character>*/> apply(final Lazy<CharSequence> η$8651) {
                              return Thunk.<String/*<Character>*/>shared(
                                        new Lazy.D<String/*<Character>*/>() {
                                          public String/*<Character>*/ call() {
                                            return η$8651.call().toString();
                                          }
                                        }
                                      );
                            }
                          },
                          Thunk.<Kind.U<Func.U<RealWorld, ?>, CharSequence>>shared(
                                new Lazy.D<Kind.U<Func.U<RealWorld, ?>, CharSequence>>() {
                                  public Kind.U<Func.U<RealWorld, ?>, CharSequence> call() {
                                    return (Kind.U<Func.U<RealWorld, ?>, CharSequence>)Thunk.<
                                          Func.U<RealWorld, CharSequence>
                                        >shared(
                                              new Lazy.D<Func.U<RealWorld, CharSequence>>() {
                                                public Func.U<RealWorld, CharSequence> call() {
                                                  return LineNumberEditText.TLineNumberEditText.getText(
                                                            arg$4.call()
                                                          );
                                                }
                                              }
                                            ).call();
                                  }
                                }
                              )
                        )
                  );
              final String/*<Character>*/ v2041$8435 = v2038$8432.apply(arg$8649).call();
              final Func.U<RealWorld, java.util.concurrent.BlockingQueue<String/*<Character>*/>> v2038$8454 =
              Concurrent.TMVar.<String/*<Character>*/>newEmpty().call();
              final java.util.concurrent.BlockingQueue<String/*<Character>*/> v2041$8457 =
              v2038$8454.apply(arg$8649).call();
              final Func.U<RealWorld, String/*<Character>*/> v2038$8522 = Concurrent.TMVar.<
                String/*<Character>*/
              >take(v2041$8457);
              final Func.U<RealWorld, String/*<Character>*/> v2038$8500 = Net.evaluateExpression(
                    v2041$8435, Thunk.<String/*<Character>*/>lazy(v2041$8413)
                  );
              final Func.U<RealWorld, Short> v4801$8479 = Concurrent.forkIO(
                    new Func.U.D<RealWorld, Short>() {
                      public Lazy<Short> apply(final Lazy<RealWorld> arg$8663) {
                        final String/*<Character>*/ v2041$8503 = v2038$8500.apply(arg$8663)
                        .call();
                        final Func.U<RealWorld, Short> v2042$8504 = Concurrent.TMVar.<
                          String/*<Character>*/
                        >put(v2041$8457, v2041$8503);
                        return Thunk.<Short>nested(
                                  new Lazy.D<Lazy<Short>>() {
                                    public Lazy<Short> call() {
                                      return v2042$8504.apply(arg$8663);
                                    }
                                  }
                                );
                      }
                    }
                  );
              final short v4804$8481 = (short)v4801$8479.apply(arg$8649).call();
              final Func.U<RealWorld, Short> v4805$8482 = (new Func.U.D<RealWorld, Short>() {
                public Lazy<Short> apply(final Lazy<RealWorld> arg$8658) {
                  final String/*<Character>*/ v2041$8525 = v2038$8522.apply(arg$8658)
                  .call();
                  final boolean $8660 = v2041$8525.startsWith("E ");
                  if ($8660) {
                    final Func.U<RealWorld, Short> v2042$8526 = EditorFragment.alertError(
                          arg$3.call(), Thunk.<String/*<Character>*/>lazy(v2041$8525)
                        );
                    return Thunk.<Short>nested(
                              new Lazy.D<Lazy<Short>>() {
                                public Lazy<Short> call() {
                                  return v2042$8526.apply(arg$8658);
                                }
                              }
                            );
                  }
                  assert ! $8660;
                  final Func.U<RealWorld, Short> v2042$8539 = ViewPager.TViewPager.setCurrentItem(
                        arg$2.call(), 0
                      );
                  return Thunk.<Short>nested(
                            new Lazy.D<Lazy<Short>>() {
                              public Lazy<Short> call() {
                                return v2042$8539.apply(arg$8658);
                              }
                            }
                          );
                }
              }).call();
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v4805$8482.apply(arg$8649);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8370.apply(arg$8645);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, android.view.View> onCreateView(
  final Lazy<java.util.concurrent.BlockingQueue<String/*<Character>*/>> arg$1,
  final Lazy<android.support.v4.view.ViewPager> arg$2, final Lazy<froid.support.v7.app.FregeAppCompatActivity> arg$3,
  final Lazy<android.support.v4.app.Fragment> arg$4, final android.view.LayoutInflater arg$5,
  final android.view.ViewGroup arg$6, final Lazy<PreludeBase.TMaybe<android.os.Bundle>> arg$7
) {
  final Func.U<RealWorld, android.view.View> v2038$8230 = LayoutInflater.TLayoutInflater.inflate(
        arg$5, io.github.mchav.tryfrege.R.layout.fragment_editor, arg$6, false
      );
  return new Func.U.D<RealWorld, android.view.View>() {
        public Lazy<android.view.View> apply(final Lazy<RealWorld> arg$8676) {
          final android.view.View v2041$8233 = v2038$8230.apply(arg$8676).call();
          final Func.U<RealWorld, android.view.View> v2038$8252 = LayoutInflater.TLayoutInflater.inflate(
                arg$5, io.github.mchav.tryfrege.R.layout.fragment_console, arg$6, false
              );
          final android.view.View v2041$8255 = v2038$8252.apply(arg$8676).call();
          final Func.U<RealWorld, me.mgottein.LineNumberEditText> v2038$8274 = LineNumberEditText.asLineNumberEditText(
                new Func.U.D<Integer, Func.U<RealWorld, android.view.View>>() {
                  public Lazy<Func.U<RealWorld, android.view.View>> apply(final Lazy<Integer> η$8680) {
                    return Thunk.<Func.U<RealWorld, android.view.View>>shared(
                              new Lazy.D<Func.U<RealWorld, android.view.View>>() {
                                public Func.U<RealWorld, android.view.View> call() {
                                  return View.TView.findViewById(v2041$8233, (int)η$8680.call());
                                }
                              }
                            );
                  }
                },
                Thunk.<Integer>lazy(io.github.mchav.tryfrege.R.id.code_editor)
              );
          final me.mgottein.LineNumberEditText v2041$8277 = v2038$8274.apply(arg$8676)
          .call();
          final Func.U<RealWorld, android.view.View> v2038$8296 = View.TView.findViewById(
                v2041$8233, io.github.mchav.tryfrege.R.id.compile_fab
              );
          final android.view.View v2041$8299 = v2038$8296.apply(arg$8676).call();
          final Func.U<RealWorld, Short> v4801$8321 = View.setViewOnClick(
                v2041$8299,
                new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                  public Lazy<Func.U<RealWorld, Short>> apply(final Lazy<android.view.View> arg$8685) {
                    return Thunk.<Func.U<RealWorld, Short>>shared(
                              new Lazy.D<Func.U<RealWorld, Short>>() {
                                public Func.U<RealWorld, Short> call() {
                                  return EditorFragment.evaluateInput(
                                            arg$1.call(), arg$2, arg$3, Thunk.<me.mgottein.LineNumberEditText>lazy(v2041$8277)
                                          );
                                }
                              }
                            );
                  }
                }
              );
          final short v4804$8323 = (short)v4801$8321.apply(arg$8676).call();
          final Func.U<RealWorld, android.view.View> v4805$8324 = Thunk.<Func.U<RealWorld, android.view.View>>shared(
                new Lazy.D<Func.U<RealWorld, android.view.View>>() {
                  public Func.U<RealWorld, android.view.View> call() {
                    return PreludeMonad.IMonad_ST.<RealWorld, android.view.View>pure(Thunk.<android.view.View>lazy(v2041$8233));
                  }
                }
              ).call();
          return Thunk.<android.view.View>nested(
                    new Lazy.D<Lazy<android.view.View>>() {
                      public Lazy<android.view.View> call() {
                        return v4805$8324.apply(arg$8676);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, android.support.v4.app.Fragment> newEditorFragment(
  final Lazy<java.util.concurrent.BlockingQueue<String/*<Character>*/>> arg$1,
  final Lazy<android.support.v4.view.ViewPager> arg$2, final Lazy<froid.support.v7.app.FregeAppCompatActivity> arg$3
) {
  return Fragment.mkFragment(
            Fragment.TFragmentDelegator.upd$onCreateView(
                  Fragment.defaultFragmentDelegator,
                  PreludeBase.TMaybe.DJust.<
                    Func.U<
                      android.support.v4.app.Fragment,
                      Func.U<
                        android.view.LayoutInflater,
                        Func.U<
                          android.view.ViewGroup,
                          Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                        >
                      >
                    >
                  >mk(
                        new Func.U.D<
                          android.support.v4.app.Fragment,
                          Func.U<
                            android.view.LayoutInflater,
                            Func.U<
                              android.view.ViewGroup,
                              Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                            >
                          >
                        >() {
                          public Lazy<Func.U<
                            android.view.LayoutInflater,
                            Func.U<
                              android.view.ViewGroup,
                              Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                            >
                          >> apply(final Lazy<android.support.v4.app.Fragment> η$8689) {
                            return new Func.U.D<
                                  android.view.LayoutInflater,
                                  Func.U<
                                    android.view.ViewGroup,
                                    Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                                  >
                                >() {
                                  public Lazy<Func.U<
                                    android.view.ViewGroup,
                                    Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                                  >> apply(final Lazy<android.view.LayoutInflater> η$8690) {
                                    return new Func.U.D<
                                          android.view.ViewGroup,
                                          Func.U<PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>>
                                        >() {
                                          public Lazy<Func.U<
                                            PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>
                                          >> apply(final Lazy<android.view.ViewGroup> η$8691) {
                                            return new Func.U.D<
                                                  PreludeBase.TMaybe<android.os.Bundle>, Func.U<RealWorld, android.view.View>
                                                >() {
                                                  public Lazy<Func.U<RealWorld, android.view.View>> apply(
                                                    final Lazy<PreludeBase.TMaybe<android.os.Bundle>> η$8692
                                                  ) {
                                                    return Thunk.<Func.U<RealWorld, android.view.View>>shared(
                                                              new Lazy.D<Func.U<RealWorld, android.view.View>>() {
                                                                public Func.U<RealWorld, android.view.View> call() {
                                                                  return EditorFragment.onCreateView(
                                                                            arg$1, arg$2, arg$3,
                                                                            η$8689, η$8690.call(), η$8691.call(),
                                                                            η$8692
                                                                          );
                                                                }
                                                              }
                                                            );
                                                  }
                                                };
                                          }
                                        };
                                  }
                                };
                          }
                        }
                      )
                )
          );
}

}
