/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/tryfrege/MainActivity.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.tryfrege;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Concurrent;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import froid.Types;
import froid.app.Activity;
import froid.content.Context;
import froid.content.Intent;
import froid.content.res.AssetManager;
import froid.content.res.Configuration;
import froid.graphics.Typeface;
import froid.os.AsyncTask;
import froid.os.Bundle;
import froid.support.v4.app.Fragment;
import froid.support.v4.app.FragmentManager;
import froid.support.v4.app.FragmentPagerAdapter;
import froid.support.v4.app.FragmentTransaction;
import froid.support.v4.view.PagerAdapter;
import froid.support.v4.view.ViewPager;
import froid.support.v7.app.ActionBar;
import froid.support.v7.app.AppCompatActivity;
import froid.support.v7.widget.Toolbar;
import froid.text.Editable;
import froid.text.TextWatcher;
import froid.util.Log;
import froid.view.ContextMenu;
import froid.view.LayoutInflater;
import froid.view.Menu;
import froid.view.MenuInflater;
import froid.view.MenuItem;
import froid.view.View;
import froid.view.ViewGroup;
import froid.view.animation.Animation;
import froid.widget.EditText;
import froid.widget.LineNumberEditText;
import froid.widget.ScrollView;
import froid.widget.TextView;
import io.github.mchav.tryfrege.ConsoleFragment;
import io.github.mchav.tryfrege.EditorFragment;
import io.github.mchav.tryfrege.Net;
import io.github.mchav.tryfrege.Utilities;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\tryfrege\\MainActivity.fr", time=1539569109288L, jmajor=1,
  jminor=7,
  imps={
    "froid.support.v7.app.AppCompatActivity", "froid.os.AsyncTask", "froid.os.Bundle",
    "io.github.mchav.tryfrege.ConsoleFragment", "frege.control.Concurrent", "froid.content.Context",
    "io.github.mchav.tryfrege.EditorFragment", "froid.support.v4.app.Fragment", "froid.support.v4.app.FragmentManager",
    "froid.support.v4.app.FragmentPagerAdapter", "froid.support.v4.app.FragmentTransaction", "froid.content.Intent",
    "froid.util.Log", "io.github.mchav.tryfrege.Net", "frege.Prelude", "frege.prelude.PreludeArrays",
    "frege.prelude.PreludeBase", "frege.prelude.PreludeIO", "frege.prelude.PreludeList", "frege.prelude.PreludeMonad",
    "frege.prelude.PreludeText", "frege.java.util.Regex", "froid.widget.TextView", "frege.java.Util",
    "io.github.mchav.tryfrege.Utilities", "froid.view.View", "froid.support.v4.view.ViewPager"
  },
  nmss={
    "AppCompatActivity", "AsyncTask", "Bundle", "C", "Concurrent", "Context", "E", "Fragment",
    "FragmentManager", "FragmentPagerAdapter", "FragmentTransaction", "Intent", "Log",
    "Net", "Prelude", "PreludeArrays", "PreludeBase", "PreludeIO", "PreludeList", "PreludeMonad",
    "PreludeText", "Regexp", "TextView", "Util", "Utilities", "View", "ViewPager"
  },
  symas={}, symcs={}, symis={}, symts={},
  symvs={
    @Meta.SymV(
      offset=801, name=@Meta.QName(pack="io.github.mchav.tryfrege.MainActivity", base="onCreate"), stri="s(su)",
      sig=2, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=1441, name=@Meta.QName(pack="io.github.mchav.tryfrege.MainActivity", base="newTryFregePager"),
      stri="s(suuu)", sig=6, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=2280, name=@Meta.QName(pack="io.github.mchav.tryfrege.MainActivity", base="getPageTitle"), stri="s(s)",
      sig=8, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=1927, name=@Meta.QName(pack="io.github.mchav.tryfrege.MainActivity", base="getItem"), stri="s(uuuus)",
      sig=10, depth=5, rkind=49
    )
  },
  symls={},
  taus={
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=0, subb=1),
    @Meta.Tau(
      kind=2, suba=0,
      tcon={@Meta.QName(kind=0, pack="froid.support.v7.app.AppCompatActivity", base="AppCompatActivity")}
    ),
    @Meta.Tau(kind=0, suba=2, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Maybe")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.os.Bundle", base="Bundle")}),
    @Meta.Tau(kind=0, suba=2, subb=6), @Meta.Tau(kind=0, suba=5, subb=7),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=9, subb=1),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=10, subb=11),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.support.v4.app.FragmentManager", base="FragmentManager")}
    ),
    @Meta.Tau(kind=0, suba=2, subb=13),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.control.Concurrent", base="MVar")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=16, subb=17), @Meta.Tau(kind=0, suba=15, subb=18),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.support.v4.view.ViewPager", base="ViewPager")}),
    @Meta.Tau(kind=0, suba=2, subb=20),
    @Meta.Tau(
      kind=2, suba=0,
      tcon={@Meta.QName(kind=0, pack="froid.support.v4.app.FragmentPagerAdapter", base="FragmentPagerAdapter")}
    ),
    @Meta.Tau(kind=0, suba=2, subb=22), @Meta.Tau(kind=0, suba=10, subb=23),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Int")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.java.Lang", base="CharSequence")}),
    @Meta.Tau(kind=0, suba=10, subb=26),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.support.v4.app.Fragment", base="Fragment")}),
    @Meta.Tau(kind=0, suba=2, subb=28), @Meta.Tau(kind=0, suba=10, subb=29)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=4), @Meta.Rho(rhofun=false, rhotau=8), @Meta.Rho(rhofun=false, rhotau=12),
    @Meta.Rho(sigma=1, rhotau=2), @Meta.Rho(sigma=0, rhotau=3), @Meta.Rho(rhofun=false, rhotau=14),
    @Meta.Rho(rhofun=false, rhotau=19), @Meta.Rho(rhofun=false, rhotau=21), @Meta.Rho(rhofun=false, rhotau=24),
    @Meta.Rho(sigma=0, rhotau=8), @Meta.Rho(sigma=5, rhotau=9), @Meta.Rho(sigma=4, rhotau=10),
    @Meta.Rho(sigma=3, rhotau=11), @Meta.Rho(rhofun=false, rhotau=25), @Meta.Rho(rhofun=false, rhotau=27),
    @Meta.Rho(sigma=7, rhotau=14), @Meta.Rho(rhofun=false, rhotau=23), @Meta.Rho(rhofun=false, rhotau=30),
    @Meta.Rho(sigma=7, rhotau=17), @Meta.Rho(sigma=9, rhotau=18), @Meta.Rho(sigma=0, rhotau=19),
    @Meta.Rho(sigma=5, rhotau=20), @Meta.Rho(sigma=4, rhotau=21)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=1), @Meta.Sigma(rho=4), @Meta.Sigma(rho=5), @Meta.Sigma(rho=6),
    @Meta.Sigma(rho=7), @Meta.Sigma(rho=12), @Meta.Sigma(rho=13), @Meta.Sigma(rho=15), @Meta.Sigma(rho=16),
    @Meta.Sigma(rho=22)
  },
  exprs={@Meta.Expr()}
)
final public class MainActivity extends froid.support.v7.app.FregeAppCompatActivity  {
  




final public static Func.U<RealWorld, CharSequence> getPageTitle(final int arg$1) {
  if (0 == arg$1) {
    return PreludeMonad.IMonad_ST.<RealWorld, CharSequence>pure(
              Thunk.<CharSequence>shared(
                    new Lazy.D<CharSequence>() {
                      public CharSequence call() {
                        return (java.lang.CharSequence)("Console");
                      }
                    }
                  )
            );
  }
  if (1 == arg$1) {
    return PreludeMonad.IMonad_ST.<RealWorld, CharSequence>pure(
              Thunk.<CharSequence>shared(
                    new Lazy.D<CharSequence>() {
                      public CharSequence call() {
                        return (java.lang.CharSequence)("Editor");
                      }
                    }
                  )
            );
  }
  throw new frege.runtime.NoMatch("getPageTitle", 57, arg$1);
}
final public static Func.U<RealWorld, android.support.v4.app.Fragment> getItem(
  final Lazy<java.util.concurrent.BlockingQueue<String/*<Character>*/>> arg$1,
  final Lazy<android.support.v4.view.ViewPager> arg$2, final Lazy<froid.support.v7.app.FregeAppCompatActivity> arg$3,
  final Lazy<android.support.v4.app.FragmentPagerAdapter> arg$4, final int arg$5
) {
  if (0 == arg$5) {
    final Func.U<RealWorld, android.support.v4.app.Fragment> v2038$8734 = ConsoleFragment.newConsoleFragment(
          arg$1
        );
    return new Func.U.D<RealWorld, android.support.v4.app.Fragment>() {
          public Lazy<android.support.v4.app.Fragment> apply(final Lazy<RealWorld> arg$8774) {
            final android.support.v4.app.Fragment v2041$8737 = v2038$8734.apply(arg$8774)
            .call();
            final Func.U<RealWorld, android.support.v4.app.Fragment> v2042$8738 = PreludeMonad.IMonad_ST.<
              RealWorld, android.support.v4.app.Fragment
            >pure(Thunk.<android.support.v4.app.Fragment>lazy(v2041$8737));
            return Thunk.<android.support.v4.app.Fragment>nested(
                      new Lazy.D<Lazy<android.support.v4.app.Fragment>>() {
                        public Lazy<android.support.v4.app.Fragment> call() {
                          return v2042$8738.apply(arg$8774);
                        }
                      }
                    );
          }
        };
  }
  if (1 == arg$5) {
    final Func.U<RealWorld, android.support.v4.app.Fragment> v2038$8756 = EditorFragment.newEditorFragment(
          arg$1, arg$2, arg$3
        );
    return new Func.U.D<RealWorld, android.support.v4.app.Fragment>() {
          public Lazy<android.support.v4.app.Fragment> apply(final Lazy<RealWorld> arg$8778) {
            final android.support.v4.app.Fragment v2041$8759 = v2038$8756.apply(arg$8778)
            .call();
            final Func.U<RealWorld, android.support.v4.app.Fragment> v2042$8760 = PreludeMonad.IMonad_ST.<
              RealWorld, android.support.v4.app.Fragment
            >pure(Thunk.<android.support.v4.app.Fragment>lazy(v2041$8759));
            return Thunk.<android.support.v4.app.Fragment>nested(
                      new Lazy.D<Lazy<android.support.v4.app.Fragment>>() {
                        public Lazy<android.support.v4.app.Fragment> call() {
                          return v2042$8760.apply(arg$8778);
                        }
                      }
                    );
          }
        };
  }
  throw new frege.runtime.NoMatch("getItem", 51, arg$5);
}
final public static Func.U<RealWorld, android.support.v4.app.FragmentPagerAdapter> newTryFregePager(
  final android.support.v4.app.FragmentManager arg$1,
  final Lazy<java.util.concurrent.BlockingQueue<String/*<Character>*/>> arg$2,
  final Lazy<android.support.v4.view.ViewPager> arg$3, final Lazy<froid.support.v7.app.FregeAppCompatActivity> arg$4
) {
  return FragmentPagerAdapter.mkFragmentPagerAdapter(
            FragmentPagerAdapter.TFragmentPagerAdapterDelegator.mk(
                  PreludeBase.TMaybe.DJust.<
                    Func.U<
                      android.support.v4.app.FragmentPagerAdapter,
                      Func.U<Integer, Func.U<RealWorld, android.support.v4.app.Fragment>>
                    >
                  >mk(
                        new Func.U.D<
                          android.support.v4.app.FragmentPagerAdapter,
                          Func.U<Integer, Func.U<RealWorld, android.support.v4.app.Fragment>>
                        >() {
                          public Lazy<Func.U<Integer, Func.U<RealWorld, android.support.v4.app.Fragment>>> apply(
                            final Lazy<android.support.v4.app.FragmentPagerAdapter> η$8781
                          ) {
                            return new Func.U.D<Integer, Func.U<RealWorld, android.support.v4.app.Fragment>>() {
                                  public Lazy<Func.U<RealWorld, android.support.v4.app.Fragment>> apply(
                                    final Lazy<Integer> η$8782
                                  ) {
                                    return Thunk.<Func.U<RealWorld, android.support.v4.app.Fragment>>shared(
                                              new Lazy.D<Func.U<RealWorld, android.support.v4.app.Fragment>>() {
                                                public Func.U<RealWorld, android.support.v4.app.Fragment> call() {
                                                  return MainActivity.getItem(arg$2, arg$3, arg$4, η$8781, (int)η$8782.call());
                                                }
                                              }
                                            );
                                  }
                                };
                          }
                        }
                      ),
                  PreludeBase.TMaybe.DJust.<Func.U<android.support.v4.app.FragmentPagerAdapter, Func.U<RealWorld, Integer>>>mk(
                        new Func.U.D<android.support.v4.app.FragmentPagerAdapter, Func.U<RealWorld, Integer>>() {
                          public Lazy<Func.U<RealWorld, Integer>> apply(
                            final Lazy<android.support.v4.app.FragmentPagerAdapter> arg$8783
                          ) {
                            return Thunk.<Func.U<RealWorld, Integer>>shared(
                                      new Lazy.D<Func.U<RealWorld, Integer>>() {
                                        public Func.U<RealWorld, Integer> call() {
                                          return PreludeMonad.IMonad_ST.<RealWorld, Integer>pure(
                                                    Thunk.<Integer>lazy(2)
                                                  );
                                        }
                                      }
                                    );
                          }
                        }
                      ),
                  PreludeBase.TMaybe.DJust.<
                    Func.U<android.support.v4.app.FragmentPagerAdapter, Func.U<Integer, Func.U<RealWorld, CharSequence>>>
                  >mk(
                        new Func.U.D<
                          android.support.v4.app.FragmentPagerAdapter, Func.U<Integer, Func.U<RealWorld, CharSequence>>
                        >() {
                          public Lazy<Func.U<Integer, Func.U<RealWorld, CharSequence>>> apply(
                            final Lazy<android.support.v4.app.FragmentPagerAdapter> arg$8784
                          ) {
                            return new Func.U.D<Integer, Func.U<RealWorld, CharSequence>>() {
                                  public Lazy<Func.U<RealWorld, CharSequence>> apply(final Lazy<Integer> η$8785) {
                                    return Thunk.<Func.U<RealWorld, CharSequence>>shared(
                                              new Lazy.D<Func.U<RealWorld, CharSequence>>() {
                                                public Func.U<RealWorld, CharSequence> call() {
                                                  return MainActivity.getPageTitle((int)η$8785.call());
                                                }
                                              }
                                            );
                                  }
                                };
                          }
                        }
                      )
                ),
            arg$1
          );
}
final public static Func.U<RealWorld, Short> onCreate(
  final froid.support.v7.app.FregeAppCompatActivity arg$1, final Lazy<PreludeBase.TMaybe<android.os.Bundle>> arg$2
) {
  final Func.U<RealWorld, java.util.concurrent.BlockingQueue<String/*<Character>*/>> v2038$8482 =
  Concurrent.TMVar.<String/*<Character>*/>newEmpty().call();
  final Func.U<RealWorld, Short> v4801$8461 = AppCompatActivity.TAppCompatActivity.setContentView(
        arg$1, io.github.mchav.tryfrege.R.layout.activity_main
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8822) {
          final short v4804$8463 = (short)v4801$8461.apply(arg$8822).call();
          final Func.U<RealWorld, Short> v4805$8464 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8787) {
              final java.util.concurrent.BlockingQueue<String/*<Character>*/> v2041$8485 =
              v2038$8482.apply(arg$8787).call();
              final Func.U<RealWorld, android.support.v4.app.FragmentManager> v2038$8550 =
              AppCompatActivity.TAppCompatActivity.getSupportFragmentManager(arg$1);
              final Func.U<RealWorld, String/*<Character>*/> v2038$8528 = Net.getSessionID
              .call();
              final Func.U<RealWorld, Short> v4801$8507 = Concurrent.forkIO(
                    new Func.U.D<RealWorld, Short>() {
                      public Lazy<Short> apply(final Lazy<RealWorld> arg$8815) {
                        final String/*<Character>*/ v2041$8531 = v2038$8528.apply(arg$8815)
                        .call();
                        final Func.U<RealWorld, Short> v2042$8532 = Concurrent.TMVar.<
                          String/*<Character>*/
                        >put(v2041$8485, v2041$8531);
                        return Thunk.<Short>nested(
                                  new Lazy.D<Lazy<Short>>() {
                                    public Lazy<Short> call() {
                                      return v2042$8532.apply(arg$8815);
                                    }
                                  }
                                );
                      }
                    }
                  );
              final short v4804$8509 = (short)v4801$8507.apply(arg$8787).call();
              final Func.U<RealWorld, Short> v4805$8510 = (new Func.U.D<RealWorld, Short>() {
                public Lazy<Short> apply(final Lazy<RealWorld> arg$8791) {
                  final android.support.v4.app.FragmentManager v2041$8553 = v2038$8550
                  .apply(arg$8791).call();
                  final Func.U<RealWorld, android.support.v7.app.ActionBar> v2038$8572 =
                  AppCompatActivity.TAppCompatActivity.getSupportActionBar(arg$1);
                  final android.support.v7.app.ActionBar v2041$8575 = v2038$8572.apply(
                        arg$8791
                      ).call();
                  final Func.U<RealWorld, android.support.v4.view.ViewPager> v2038$8666 =
                  ViewPager.asViewPager(
                        new Func.U.D<Integer, Func.U<RealWorld, android.view.View>>() {
                          public Lazy<Func.U<RealWorld, android.view.View>> apply(final Lazy<Integer> η$8795) {
                            return Thunk.<Func.U<RealWorld, android.view.View>>shared(
                                      new Lazy.D<Func.U<RealWorld, android.view.View>>() {
                                        public Func.U<RealWorld, android.view.View> call() {
                                          return AppCompatActivity.TAppCompatActivity.findViewById(
                                                    arg$1, (int)η$8795.call()
                                                  );
                                        }
                                      }
                                    );
                          }
                        },
                        Thunk.<Integer>lazy(io.github.mchav.tryfrege.R.id.try_frege_pager)
                      );
                  final Func.U<RealWorld, Short> v4801$8645 = ActionBar.TActionBar.setDisplayUseLogoEnabled(
                        v2041$8575, true
                      );
                  final Func.U<RealWorld, Short> v4801$8621 = ActionBar.TActionBar.setDisplayShowHomeEnabled(
                        v2041$8575, true
                      );
                  final Func.U<RealWorld, Short> v4801$8597 = ActionBar.TActionBar.setLogo(
                        v2041$8575, io.github.mchav.tryfrege.R.mipmap.ic_launcher
                      );
                  final short v4804$8599 = (short)v4801$8597.apply(arg$8791).call();
                  final Func.U<RealWorld, Short> v4805$8600 = (new Func.U.D<RealWorld, Short>() {
                    public Lazy<Short> apply(final Lazy<RealWorld> arg$8809) {
                      final short v4804$8623 = (short)v4801$8621.apply(arg$8809).call();
                      final Func.U<RealWorld, Short> v4805$8624 = (new Func.U.D<RealWorld, Short>() {
                        public Lazy<Short> apply(final Lazy<RealWorld> arg$8805) {
                          final short v4804$8647 = (short)v4801$8645.apply(arg$8805).call();
                          final Func.U<RealWorld, Short> v4805$8648 = (new Func.U.D<RealWorld, Short>() {
                            public Lazy<Short> apply(final Lazy<RealWorld> arg$8797) {
                              final android.support.v4.view.ViewPager v2041$8669 = v2038$8666
                              .apply(arg$8797).call();
                              final Func.U<RealWorld, android.support.v4.app.FragmentPagerAdapter> v2038$8688 =
                              MainActivity.newTryFregePager(
                                    v2041$8553,
                                    Thunk.<java.util.concurrent.BlockingQueue<String/*<Character>*/>>lazy(
                                          v2041$8485
                                        ),
                                    Thunk.<android.support.v4.view.ViewPager>lazy(v2041$8669),
                                    Thunk.<froid.support.v7.app.FregeAppCompatActivity>lazy(
                                          arg$1
                                        )
                                  );
                              final android.support.v4.app.FragmentPagerAdapter v2041$8691 =
                              v2038$8688.apply(arg$8797).call();
                              final Func.U<RealWorld, Short> v4801$8713 = ViewPager.TViewPager.setAdapter(
                                    v2041$8669, (android.support.v4.view.PagerAdapter)v2041$8691
                                  );
                              final short v4804$8715 = (short)v4801$8713.apply(arg$8797)
                              .call();
                              final Func.U<RealWorld, Short> v4805$8716 = Thunk.<Func.U<RealWorld, Short>>shared(
                                    new Lazy.D<Func.U<RealWorld, Short>>() {
                                      public Func.U<RealWorld, Short> call() {
                                        return ViewPager.TViewPager.setCurrentItem(v2041$8669, 0);
                                      }
                                    }
                                  ).call();
                              return Thunk.<Short>nested(
                                        new Lazy.D<Lazy<Short>>() {
                                          public Lazy<Short> call() {
                                            return v4805$8716.apply(arg$8797);
                                          }
                                        }
                                      );
                            }
                          }).call();
                          return Thunk.<Short>nested(
                                    new Lazy.D<Lazy<Short>>() {
                                      public Lazy<Short> call() {
                                        return v4805$8648.apply(arg$8805);
                                      }
                                    }
                                  );
                        }
                      }).call();
                      return Thunk.<Short>nested(
                                new Lazy.D<Lazy<Short>>() {
                                  public Lazy<Short> call() {
                                    return v4805$8624.apply(arg$8809);
                                  }
                                }
                              );
                    }
                  }).call();
                  return Thunk.<Short>nested(
                            new Lazy.D<Lazy<Short>>() {
                              public Lazy<Short> call() {
                                return v4805$8600.apply(arg$8791);
                              }
                            }
                          );
                }
              }).call();
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v4805$8510.apply(arg$8787);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8464.apply(arg$8822);
                      }
                    }
                  );
        }
      };
}

}
