/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/tryfrege/Net.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.tryfrege;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Concurrent;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import froid.Types;
import froid.content.Context;
import froid.content.res.AssetManager;
import froid.util.Log;
import froid.view.View;
import io.github.mchav.tryfrege.Utilities;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\tryfrege\\Net.fr", time=1539569105260L, jmajor=1,
  jminor=7,
  imps={
    "froid.util.Log", "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase",
    "frege.prelude.PreludeIO", "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText",
    "frege.java.util.Regex", "io.github.mchav.tryfrege.Utilities"
  },
  nmss={
    "Log", "Prelude", "PreludeArrays", "PreludeBase", "PreludeIO", "PreludeList", "PreludeMonad",
    "PreludeText", "Regexp", "Utilities"
  },
  symas={}, symcs={}, symis={}, symts={},
  symvs={
    @Meta.SymV(
      offset=1468, name=@Meta.QName(pack="io.github.mchav.tryfrege.Net", base="parseXmlResult"), stri="s(u)",
      sig=1, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=1856, name=@Meta.QName(pack="io.github.mchav.tryfrege.Net", base="getNodeString"), stri="s(ss)",
      sig=4, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=115, name=@Meta.QName(pack="io.github.mchav.tryfrege.Net", base="getSessionID"), stri="u",
      sig=5, depth=0, rkind=36
    ),
    @Meta.SymV(
      offset=715, name=@Meta.QName(pack="io.github.mchav.tryfrege.Net", base="extractSession"), stri="s(s)",
      sig=7, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=824, name=@Meta.QName(pack="io.github.mchav.tryfrege.Net", base="evaluateExpression"), stri="s(su)",
      sig=8, depth=2, rkind=49
    )
  },
  symls={},
  taus={
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.java.IO", base="InputStream")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=1, subb=2),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=4, subb=5), @Meta.Tau(kind=0, suba=3, subb=6),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=0, suba=8, subb=2),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.tryfrege.Utilities", base="NodeList")}),
    @Meta.Tau(kind=0, suba=9, subb=10),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Int")})
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=0), @Meta.Rho(rhofun=false, rhotau=7), @Meta.Rho(sigma=0, rhotau=1),
    @Meta.Rho(rhofun=false, rhotau=11), @Meta.Rho(rhofun=false, rhotau=12), @Meta.Rho(sigma=3, rhotau=1),
    @Meta.Rho(sigma=2, rhotau=5), @Meta.Rho(rhofun=false, rhotau=6), @Meta.Rho(sigma=6, rhotau=7),
    @Meta.Rho(sigma=6, rhotau=1), @Meta.Rho(sigma=6, rhotau=9)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=2), @Meta.Sigma(rho=3), @Meta.Sigma(rho=4), @Meta.Sigma(rho=6),
    @Meta.Sigma(rho=1), @Meta.Sigma(rho=7), @Meta.Sigma(rho=8), @Meta.Sigma(rho=10)
  },
  exprs={@Meta.Expr()}
)
final public class Net  {
  




final public static Func.U<RealWorld, String/*<Character>*/> getNodeString(final org.w3c.dom.NodeList arg$1, final int arg$2) {
  final Func.U<RealWorld, PreludeBase.TMaybe<org.w3c.dom.Node>> v2038$8306 = Utilities.TNodeList.item(
        arg$1, arg$2
      );
  return new Func.U.D<RealWorld, String/*<Character>*/>() {
        public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8817) {
          final PreludeBase.TMaybe<org.w3c.dom.Node> v2041$8309 = v2038$8306.apply(arg$8817)
          .call();
          final PreludeBase.TMaybe.DJust<org.w3c.dom.Node> $8819 = v2041$8309.asJust();
          if ($8819 != null) {
            final Func.U<RealWorld, String/*<Character>*/> v2042$8310 = Func.<RealWorld, String/*<Character>*/>coerceU(
                  PreludeMonad.<Func.U<RealWorld, ?>, String/*<Character>*/, String/*<Character>*/>liftM(
                        PreludeMonad.IMonad_ST.<RealWorld>mk(),
                        new Func.U.D<String/*<Character>*/, String/*<Character>*/>() {
                          public Lazy<String/*<Character>*/> apply(final Lazy<String/*<Character>*/> η$8820) {
                            return Thunk.<String/*<Character>*/>shared(
                                      new Lazy.D<String/*<Character>*/>() {
                                        public String/*<Character>*/ call() {
                                          return η$8820.call().trim();
                                        }
                                      }
                                    );
                          }
                        },
                        Thunk.<Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>>shared(
                              new Lazy.D<Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>>() {
                                public Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/> call() {
                                  return (Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>)Thunk.<
                                        Func.U<RealWorld, String/*<Character>*/>
                                      >shared(
                                            new Lazy.D<Func.U<RealWorld, String/*<Character>*/>>() {
                                              public Func.U<RealWorld, String/*<Character>*/> call() {
                                                return Utilities.TNode.getTextContent(
                                                          $8819.mem1.call()
                                                        );
                                              }
                                            }
                                          ).call();
                                }
                              }
                            )
                      )
                );
            return Thunk.<String/*<Character>*/>nested(
                      new Lazy.D<Lazy<String/*<Character>*/>>() {
                        public Lazy<String/*<Character>*/> call() {
                          return v2042$8310.apply(arg$8817);
                        }
                      }
                    );
          }
          final PreludeBase.TMaybe.DNothing<org.w3c.dom.Node> $8822 = v2041$8309.asNothing();
          assert $8822 != null;
          final Func.U<RealWorld, String/*<Character>*/> v2042$8323 = PreludeMonad.IMonad_ST.<
            RealWorld, String/*<Character>*/
          >pure(Thunk.<String/*<Character>*/>lazy(""));
          return Thunk.<String/*<Character>*/>nested(
                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                      public Lazy<String/*<Character>*/> call() {
                        return v2042$8323.apply(arg$8817);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, String/*<Character>*/> parseXmlResult(final Lazy<java.io.InputStream> arg$1) {
  final Func.U<RealWorld, javax.xml.parsers.DocumentBuilderFactory> v2038$8150 = Utilities.TDocumentBuilderFactory.newInstance(
        PreludeBase.TUnit.Unit
      );
  return new Func.U.D<RealWorld, String/*<Character>*/>() {
        public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8825) {
          final javax.xml.parsers.DocumentBuilderFactory v2041$8153 = v2038$8150.apply(
                arg$8825
              ).call();
          final Func.U<RealWorld, javax.xml.parsers.DocumentBuilder> v2038$8172 =
          Utilities.TDocumentBuilderFactory.newDocumentBuilder(v2041$8153);
          final javax.xml.parsers.DocumentBuilder v2041$8175 = v2038$8172.apply(arg$8825)
          .call();
          final Func.U<RealWorld, org.w3c.dom.Document> v2038$8194 = Utilities.TDocumentBuilder.parse(
                v2041$8175, arg$1.call()
              );
          final org.w3c.dom.Document v2041$8197 = v2038$8194.apply(arg$8825).call();
          final Func.U<RealWorld, org.w3c.dom.Element> v2038$8216 = Utilities.TDocument.getDocumentElement(
                v2041$8197
              );
          final org.w3c.dom.Element v2041$8219 = v2038$8216.apply(arg$8825).call();
          final Func.U<RealWorld, org.w3c.dom.NodeList> v2038$8262 = Utilities.TDocument.getElementsByTagName(
                v2041$8197, "text"
              );
          final Func.U<RealWorld, Short> v4801$8241 = Utilities.TElement.normalize(v2041$8219);
          final short v4804$8243 = (short)v4801$8241.apply(arg$8825).call();
          final Func.U<RealWorld, String/*<Character>*/> v4805$8244 = (new Func.U.D<RealWorld, String/*<Character>*/>() {
            public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8834) {
              final org.w3c.dom.NodeList v2041$8265 = v2038$8262.apply(arg$8834).call();
              final Func.U<RealWorld, PreludeBase.TList<String/*<Character>*/>> v2038$8284 =
              Func.<RealWorld, PreludeBase.TList<String/*<Character>*/>>coerceU(
                    PreludeMonad.<Func.U<RealWorld, ?>, String/*<Character>*/, Integer>mapM(
                          PreludeMonad.IMonad_ST.<RealWorld>mk(), PreludeMonad.IMonad_ST.<RealWorld>mk(),
                          new Func.U.D<Integer, Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>>() {
                            public Lazy<Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>> apply(
                              final Lazy<Integer> η$8836
                            ) {
                              return Thunk.<Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>>shared(
                                        new Lazy.D<Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>>() {
                                          public Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/> call() {
                                            return (Kind.U<Func.U<RealWorld, ?>, String/*<Character>*/>)Thunk.<
                                                  Func.U<RealWorld, String/*<Character>*/>
                                                >shared(
                                                      new Lazy.D<Func.U<RealWorld, String/*<Character>*/>>() {
                                                        public Func.U<RealWorld, String/*<Character>*/> call() {
                                                          return Net.getNodeString(v2041$8265, (int)η$8836.call());
                                                        }
                                                      }
                                                    ).call();
                                          }
                                        }
                                      );
                            }
                          },
                          PreludeBase.IEnum_Int.enumFromTo(0, 10)
                        )
                  );
              final PreludeBase.TList<String/*<Character>*/> v2041$8287 = v2038$8284.apply(
                    arg$8834
                  ).call();
              final Func.U<RealWorld, String/*<Character>*/> v2042$8288 = PreludeMonad.IMonad_ST.<
                RealWorld, String/*<Character>*/
              >pure(
                    Thunk.<String/*<Character>*/>shared(
                          new Lazy.D<String/*<Character>*/>() {
                            public String/*<Character>*/ call() {
                              return PreludeText.unlines(v2041$8287).trim();
                            }
                          }
                        )
                  );
              return Thunk.<String/*<Character>*/>nested(
                        new Lazy.D<Lazy<String/*<Character>*/>>() {
                          public Lazy<String/*<Character>*/> call() {
                            return v2042$8288.apply(arg$8834);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<String/*<Character>*/>nested(
                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                      public Lazy<String/*<Character>*/> call() {
                        return v4805$8244.apply(arg$8825);
                      }
                    }
                  );
        }
      };
}
final public static String/*<Character>*/ extractSession(final String/*<Character>*/ arg$1) {
  return arg$1.substring(arg$1.indexOf("=", 0) + 1, arg$1.indexOf(";", 0));
}
final public static Lazy<Func.U<RealWorld, String/*<Character>*/>> getSessionID = Thunk.<
  Func.U<RealWorld, String/*<Character>*/>
>shared(
      new Lazy.D<Func.U<RealWorld, String/*<Character>*/>>() {
        public Func.U<RealWorld, String/*<Character>*/> call() {
          final Func.U<RealWorld, java.net.URL> v2038$8329 = Utilities.TURL.$new("http://try.frege-lang.org/eval?cmd=&stdin=");
          return new Func.U.D<RealWorld, String/*<Character>*/>() {
                public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8844) {
                  final java.net.URL v2041$8332 = v2038$8329.apply(arg$8844).call();
                  final Func.U<RealWorld, java.net.URLConnection> v2038$8351 = Utilities.TURL.openConnection(
                        v2041$8332
                      );
                  final java.net.URLConnection v2041$8354 = v2038$8351.apply(arg$8844)
                  .call();
                  final Func.U<
                    RealWorld, PreludeBase.TEither<java.lang.ClassCastException, java.net.HttpURLConnection>
                  > v2038$8395 = Utilities.toHttpURLConnection(v2041$8354);
                  final PreludeBase.TEither<java.lang.ClassCastException, java.net.HttpURLConnection> v2041$8398 =
                  v2038$8395.apply(arg$8844).call();
                  final Func.U<RealWorld, java.net.HttpURLConnection> v2042$8399 = PreludeBase.<
                    Func.U<RealWorld, java.net.HttpURLConnection>, java.lang.ClassCastException, java.net.HttpURLConnection
                  >either(
                        new Func.U.D<java.lang.ClassCastException, Func.U<RealWorld, java.net.HttpURLConnection>>() {
                          public Lazy<Func.U<RealWorld, java.net.HttpURLConnection>> apply(
                            final Lazy<java.lang.ClassCastException> arg$8850
                          ) {
                            return Thunk.<Func.U<RealWorld, java.net.HttpURLConnection>>shared(
                                      new Lazy.D<Func.U<RealWorld, java.net.HttpURLConnection>>() {
                                        public Func.U<RealWorld, java.net.HttpURLConnection> call() {
                                          return PreludeBase.<Func.U<RealWorld, java.net.HttpURLConnection>>error(
                                                    "Cast failed."
                                                  );
                                        }
                                      }
                                    );
                          }
                        },
                        new Func.U.D<java.net.HttpURLConnection, Func.U<RealWorld, java.net.HttpURLConnection>>() {
                          public Lazy<Func.U<RealWorld, java.net.HttpURLConnection>> apply(
                            final Lazy<java.net.HttpURLConnection> η$8851
                          ) {
                            return Thunk.<Func.U<RealWorld, java.net.HttpURLConnection>>shared(
                                      new Lazy.D<Func.U<RealWorld, java.net.HttpURLConnection>>() {
                                        public Func.U<RealWorld, java.net.HttpURLConnection> call() {
                                          return PreludeMonad.IMonad_ST.<RealWorld, java.net.HttpURLConnection>pure(
                                                    η$8851
                                                  );
                                        }
                                      }
                                    );
                          }
                        },
                        v2041$8398
                      ).call();
                  final java.net.HttpURLConnection v2041$8376 = v2042$8399.apply(arg$8844)
                  .call();
                  final Func.U<RealWorld, Integer> v2038$8496 = Utilities.THttpURLConnection.getResponseCode(
                        v2041$8376
                      );
                  final Func.U<RealWorld, Short> v4801$8475 = Utilities.THttpURLConnection.setDoOutput(
                        v2041$8376, true
                      );
                  final Func.U<RealWorld, Short> v4801$8451 = Utilities.THttpURLConnection.setRequestProperty(
                        v2041$8376, "Accept-Charset", "UTF-8"
                      );
                  final Func.U<RealWorld, Short> v4801$8427 = Utilities.THttpURLConnection.setRequestMethod(
                        v2041$8376, "GET"
                      );
                  final short v4804$8429 = (short)v4801$8427.apply(arg$8844).call();
                  final Func.U<RealWorld, String/*<Character>*/> v4805$8430 = (new Func.U.D<
                    RealWorld, String/*<Character>*/
                  >() {
                    public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8874) {
                      final short v4804$8453 = (short)v4801$8451.apply(arg$8874).call();
                      final Func.U<RealWorld, String/*<Character>*/> v4805$8454 = (new Func.U.D<
                        RealWorld, String/*<Character>*/
                      >() {
                        public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8870) {
                          final short v4804$8477 = (short)v4801$8475.apply(arg$8870).call();
                          final Func.U<RealWorld, String/*<Character>*/> v4805$8478 =
                          (new Func.U.D<RealWorld, String/*<Character>*/>() {
                            public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8855) {
                              final int v2041$8499 = (int)v2038$8496.apply(arg$8855).call();
                              final Func.U<
                                RealWorld, java.util.Map<String/*<Character>*/, java.util.List<String/*<Character>*/>>
                              > v2038$8518 = Utilities.THttpURLConnection.<RealWorld>getHeaderFields(
                                    v2041$8376
                                  );
                              final java.util.Map<String/*<Character>*/, java.util.List<String/*<Character>*/>> v2041$8521 =
                              v2038$8518.apply(arg$8855).call();
                              final Func.U<RealWorld, PreludeBase.TMaybe<java.util.List<String/*<Character>*/>>> v2038$8540 =
                              Util.TMap.<java.util.List<String/*<Character>*/>, String/*<Character>*/, RealWorld>get(
                                    v2041$8521, "Set-Cookie"
                                  );
                              final PreludeBase.TMaybe<java.util.List<String/*<Character>*/>> v2041$8543 =
                              v2038$8540.apply(arg$8855).call();
                              final PreludeBase.TMaybe.DJust<java.util.List<String/*<Character>*/>> $8861 =
                              v2041$8543.asJust();
                              if ($8861 != null) {
                                final java.util.List<String/*<Character>*/> vals$7746 =
                                $8861.mem1.call();
                                final Func.U<RealWorld, PreludeBase.TMaybe<String/*<Character>*/>> v2038$8562 =
                                Util.TList.<String/*<Character>*/, RealWorld>get(vals$7746, 0);
                                final PreludeBase.TMaybe<String/*<Character>*/> v2041$8565 =
                                v2038$8562.apply(arg$8855).call();
                                final PreludeBase.TMaybe.DJust<String/*<Character>*/> $8865 =
                                v2041$8565.asJust();
                                if ($8865 != null) {
                                  final Func.U<RealWorld, String/*<Character>*/> v2042$8566 =
                                  PreludeMonad.IMonad_ST.<RealWorld, String/*<Character>*/>pure(
                                        Thunk.<String/*<Character>*/>shared(
                                              new Lazy.D<String/*<Character>*/>() {
                                                public String/*<Character>*/ call() {
                                                  return Net.extractSession($8865.mem1.call());
                                                }
                                              }
                                            )
                                      );
                                  return Thunk.<String/*<Character>*/>nested(
                                            new Lazy.D<Lazy<String/*<Character>*/>>() {
                                              public Lazy<String/*<Character>*/> call() {
                                                return v2042$8566.apply(arg$8855);
                                              }
                                            }
                                          );
                                }
                                final Func.U<RealWorld, String/*<Character>*/> v2042$8579 =
                                PreludeMonad.IMonadFail_ST.<RealWorld, String/*<Character>*/>fail(
                                      "pattern failed in do block, io.github.mchav.tryfrege.Net line 19"
                                    );
                                return Thunk.<String/*<Character>*/>nested(
                                          new Lazy.D<Lazy<String/*<Character>*/>>() {
                                            public Lazy<String/*<Character>*/> call() {
                                              return v2042$8579.apply(arg$8855);
                                            }
                                          }
                                        );
                              }
                              final Func.U<RealWorld, String/*<Character>*/> v2042$8580 =
                              PreludeMonad.IMonadFail_ST.<RealWorld, String/*<Character>*/>fail(
                                    "pattern failed in do block, io.github.mchav.tryfrege.Net line 18"
                                  );
                              return Thunk.<String/*<Character>*/>nested(
                                        new Lazy.D<Lazy<String/*<Character>*/>>() {
                                          public Lazy<String/*<Character>*/> call() {
                                            return v2042$8580.apply(arg$8855);
                                          }
                                        }
                                      );
                            }
                          }).call();
                          return Thunk.<String/*<Character>*/>nested(
                                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                                      public Lazy<String/*<Character>*/> call() {
                                        return v4805$8478.apply(arg$8870);
                                      }
                                    }
                                  );
                        }
                      }).call();
                      return Thunk.<String/*<Character>*/>nested(
                                new Lazy.D<Lazy<String/*<Character>*/>>() {
                                  public Lazy<String/*<Character>*/> call() {
                                    return v4805$8454.apply(arg$8874);
                                  }
                                }
                              );
                    }
                  }).call();
                  return Thunk.<String/*<Character>*/>nested(
                            new Lazy.D<Lazy<String/*<Character>*/>>() {
                              public Lazy<String/*<Character>*/> call() {
                                return v4805$8430.apply(arg$8844);
                              }
                            }
                          );
                }
              };
        }
      }
    );
final public static Func.U<RealWorld, String/*<Character>*/> evaluateExpression(
  final String/*<Character>*/ arg$1, final Lazy<String/*<Character>*/> arg$2
) {
  final Func.U<RealWorld, String/*<Character>*/> v2038$8586 = Utilities.TURLEncoder.encode(
        arg$1, "UTF-8"
      );
  return new Func.U.D<RealWorld, String/*<Character>*/>() {
        public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8881) {
          final String/*<Character>*/ v2041$8589 = v2038$8586.apply(arg$8881).call();
          final Func.U<RealWorld, java.net.URL> v2038$8608 = Utilities.TURL.$new(
                "http://try.frege-lang.org/eval?cmd=" + (v2041$8589 + "&stdin=")
              );
          final java.net.URL v2041$8611 = v2038$8608.apply(arg$8881).call();
          final Func.U<RealWorld, java.net.URLConnection> v2038$8630 = Utilities.TURL.openConnection(
                v2041$8611
              );
          final java.net.URLConnection v2041$8633 = v2038$8630.apply(arg$8881).call();
          final Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, java.net.HttpURLConnection>> v2038$8674 =
          Utilities.toHttpURLConnection(v2041$8633);
          final PreludeBase.TEither<java.lang.ClassCastException, java.net.HttpURLConnection> v2041$8677 =
          v2038$8674.apply(arg$8881).call();
          final Func.U<RealWorld, java.net.HttpURLConnection> v2042$8678 = PreludeBase.<
            Func.U<RealWorld, java.net.HttpURLConnection>, java.lang.ClassCastException, java.net.HttpURLConnection
          >either(
                new Func.U.D<java.lang.ClassCastException, Func.U<RealWorld, java.net.HttpURLConnection>>() {
                  public Lazy<Func.U<RealWorld, java.net.HttpURLConnection>> apply(
                    final Lazy<java.lang.ClassCastException> arg$8889
                  ) {
                    return Thunk.<Func.U<RealWorld, java.net.HttpURLConnection>>shared(
                              new Lazy.D<Func.U<RealWorld, java.net.HttpURLConnection>>() {
                                public Func.U<RealWorld, java.net.HttpURLConnection> call() {
                                  return PreludeBase.<Func.U<RealWorld, java.net.HttpURLConnection>>error(
                                            "Cast failed."
                                          );
                                }
                              }
                            );
                  }
                },
                new Func.U.D<java.net.HttpURLConnection, Func.U<RealWorld, java.net.HttpURLConnection>>() {
                  public Lazy<Func.U<RealWorld, java.net.HttpURLConnection>> apply(
                    final Lazy<java.net.HttpURLConnection> η$8890
                  ) {
                    return Thunk.<Func.U<RealWorld, java.net.HttpURLConnection>>shared(
                              new Lazy.D<Func.U<RealWorld, java.net.HttpURLConnection>>() {
                                public Func.U<RealWorld, java.net.HttpURLConnection> call() {
                                  return PreludeMonad.IMonad_ST.<RealWorld, java.net.HttpURLConnection>pure(
                                            η$8890
                                          );
                                }
                              }
                            );
                  }
                },
                v2041$8677
              ).call();
          final java.net.HttpURLConnection v2041$8655 = v2042$8678.apply(arg$8881).call();
          final Func.U<RealWorld, java.io.InputStream> v2038$8799 = Utilities.THttpURLConnection.getInputStream(
                v2041$8655
              );
          final Func.U<RealWorld, Short> v4801$8778 = Utilities.THttpURLConnection.setDoOutput(
                v2041$8655, true
              );
          final Func.U<RealWorld, Short> v4801$8754 = Utilities.THttpURLConnection.setRequestProperty(
                v2041$8655, "Cookie", "JSESSIONID=" + arg$2.call()
              );
          final Func.U<RealWorld, Short> v4801$8730 = Utilities.THttpURLConnection.setRequestProperty(
                v2041$8655, "Accept-Charset", "UTF-8"
              );
          final Func.U<RealWorld, Short> v4801$8706 = Utilities.THttpURLConnection.setRequestMethod(
                v2041$8655, "GET"
              );
          final short v4804$8708 = (short)v4801$8706.apply(arg$8881).call();
          final Func.U<RealWorld, String/*<Character>*/> v4805$8709 = (new Func.U.D<RealWorld, String/*<Character>*/>() {
            public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8906) {
              final short v4804$8732 = (short)v4801$8730.apply(arg$8906).call();
              final Func.U<RealWorld, String/*<Character>*/> v4805$8733 = (new Func.U.D<
                RealWorld, String/*<Character>*/
              >() {
                public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8902) {
                  final short v4804$8756 = (short)v4801$8754.apply(arg$8902).call();
                  final Func.U<RealWorld, String/*<Character>*/> v4805$8757 = (new Func.U.D<
                    RealWorld, String/*<Character>*/
                  >() {
                    public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8898) {
                      final short v4804$8780 = (short)v4801$8778.apply(arg$8898).call();
                      final Func.U<RealWorld, String/*<Character>*/> v4805$8781 = (new Func.U.D<
                        RealWorld, String/*<Character>*/
                      >() {
                        public Lazy<String/*<Character>*/> apply(final Lazy<RealWorld> arg$8894) {
                          final java.io.InputStream v2041$8802 = v2038$8799.apply(arg$8894)
                          .call();
                          final Func.U<RealWorld, String/*<Character>*/> v2042$8803 =
                          Net.parseXmlResult(Thunk.<java.io.InputStream>lazy(v2041$8802));
                          return Thunk.<String/*<Character>*/>nested(
                                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                                      public Lazy<String/*<Character>*/> call() {
                                        return v2042$8803.apply(arg$8894);
                                      }
                                    }
                                  );
                        }
                      }).call();
                      return Thunk.<String/*<Character>*/>nested(
                                new Lazy.D<Lazy<String/*<Character>*/>>() {
                                  public Lazy<String/*<Character>*/> call() {
                                    return v4805$8781.apply(arg$8898);
                                  }
                                }
                              );
                    }
                  }).call();
                  return Thunk.<String/*<Character>*/>nested(
                            new Lazy.D<Lazy<String/*<Character>*/>>() {
                              public Lazy<String/*<Character>*/> call() {
                                return v4805$8757.apply(arg$8902);
                              }
                            }
                          );
                }
              }).call();
              return Thunk.<String/*<Character>*/>nested(
                        new Lazy.D<Lazy<String/*<Character>*/>>() {
                          public Lazy<String/*<Character>*/> call() {
                            return v4805$8733.apply(arg$8906);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<String/*<Character>*/>nested(
                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                      public Lazy<String/*<Character>*/> call() {
                        return v4805$8709.apply(arg$8881);
                      }
                    }
                  );
        }
      };
}

}
